const tools = ['cargo-audit', 'cargo-geiger', 'clippy', 'solana-fender'];

const rules = [
  {
    id: 'SWC-001',
    tool: 'solana-fender',
    severity: 'critical',
    title: 'Missing account owner check',
    description: 'An account appears to be used without validating ownership.',
    remediation: 'Use Anchor account constraints such as owner, has_one, or explicit owner checks before mutating account data.',
    pattern: /\/\/\s*(todo|fixme|missing).*owner|AccountInfo<'info>[\s\S]{0,240}try_borrow_mut_data/i,
  },
  {
    id: 'SWC-002',
    tool: 'solana-fender',
    severity: 'critical',
    title: 'Unchecked signer authorization',
    description: 'Instruction authorization may depend on a caller-provided account without a signer requirement.',
    remediation: 'Require Signer accounts for authorities and add has_one or address constraints for privileged roles.',
    pattern: /pub\s+(admin|authority|owner):\s*(AccountInfo|UncheckedAccount)|is_signer\s*==\s*false/i,
  },
  {
    id: 'SWC-003',
    tool: 'solana-fender',
    severity: 'high',
    title: 'Unchecked arithmetic on account balance',
    description: 'Direct arithmetic on balances can overflow or underflow in release builds.',
    remediation: 'Replace direct arithmetic with checked_add, checked_sub, checked_mul, and return a domain error on None.',
    pattern: /\.(amount|balance|shares|supply)\s*[-+*\/]=|let\s+\w+\s*=\s*\w+\s*[*+-]\s*\w+\s*;/,
  },
  {
    id: 'SWC-004',
    tool: 'solana-fender',
    severity: 'medium',
    title: 'PDA seeds are not explicitly validated',
    description: 'A PDA account is present without nearby seed and bump constraints.',
    remediation: 'Use #[account(seeds = [...], bump)] and verify all user-controlled seed components.',
    pattern: /pub\s+\w+:\s*Account<'info,\s*\w+>[\s\S]{0,160}(?!seeds\s*=)/,
  },
  {
    id: 'SWC-005',
    tool: 'solana-fender',
    severity: 'medium',
    title: 'Unchecked account used',
    description: 'UncheckedAccount bypasses Anchor type and owner validation.',
    remediation: 'Prefer typed Account, Program, or Sysvar accounts. If UncheckedAccount is required, validate key, owner, and data length.',
    pattern: /UncheckedAccount<'info>|AccountInfo<'info>/,
  },
  {
    id: 'SWC-006',
    tool: 'solana-fender',
    severity: 'high',
    title: 'Unsafe account close pattern',
    description: 'Manual lamport movement or data reassignment can leave stale or reusable accounts.',
    remediation: 'Use Anchor close constraints and ensure account discriminators cannot be reused.',
    pattern: /\*\*.*lamports\.borrow_mut\(\)\s*\+=|\*\*.*lamports\.borrow_mut\(\)\s*=/,
  },
  {
    id: 'SWC-007',
    tool: 'solana-fender',
    severity: 'medium',
    title: 'Clock sysvar used without freshness guard',
    description: 'Time-dependent logic can be manipulated if stale or boundary conditions are not handled.',
    remediation: 'Validate acceptable timestamp ranges and avoid single-slot assumptions in financial logic.',
    pattern: /Clock::get\(\)|Sysvar<'info,\s*Clock>/,
  },
  {
    id: 'SWC-008',
    tool: 'solana-fender',
    severity: 'high',
    title: 'Authority transfer lacks explicit validation',
    description: 'Authority changes are security-critical and must require current authority approval.',
    remediation: 'Require the current authority as Signer and emit an event for authority changes.',
    pattern: /(set|transfer|update)_authority|authority\s*=\s*new_authority/i,
  },
  {
    id: 'SWC-009',
    tool: 'solana-fender',
    severity: 'medium',
    title: 'Potential duplicate mutable accounts',
    description: 'Multiple mutable accounts in one instruction can alias unless distinct keys are checked.',
    remediation: 'Add key inequality constraints for accounts that must be distinct.',
    pattern: /#\[account\(mut\)\][\s\S]{0,120}#\[account\(mut\)\]/,
  },
  {
    id: 'SWC-010',
    tool: 'solana-fender',
    severity: 'low',
    title: 'Hardcoded program ID',
    description: 'Hardcoded program IDs make environment promotion error-prone.',
    remediation: 'Keep program IDs in environment-specific config and verify deployment metadata.',
    pattern: /declare_id!\s*\(\s*"[A-Za-z0-9]{32,44}"\s*\)/,
  },
  {
    id: 'CLY-001',
    tool: 'clippy',
    severity: 'low',
    title: 'Panic-prone unwrap used',
    description: 'unwrap can panic and abort execution paths unexpectedly.',
    remediation: 'Use ? for propagation or map errors into explicit program errors.',
    pattern: /\.unwrap\(\)/,
  },
  {
    id: 'CLY-002',
    tool: 'clippy',
    severity: 'low',
    title: 'Panic-prone expect used',
    description: 'expect can panic and should be limited to unreachable states.',
    remediation: 'Return a typed error instead of panicking in instruction handlers.',
    pattern: /\.expect\(/,
  },
  {
    id: 'CLY-003',
    tool: 'clippy',
    severity: 'medium',
    title: 'Integer boundary constant used',
    description: 'Boundary constants often indicate edge-case arithmetic that needs explicit guards.',
    remediation: 'Add bounds checks and tests for min/max values.',
    pattern: /\bu(8|16|32|64|128)::MAX\b|\bi(8|16|32|64|128)::(MIN|MAX)\b/,
  },
  {
    id: 'CLY-004',
    tool: 'clippy',
    severity: 'info',
    title: 'TODO or FIXME comment',
    description: 'Incomplete security-sensitive code should be resolved before launch.',
    remediation: 'Resolve the comment or convert it into a tracked issue with an owner.',
    pattern: /\/\/\s*(todo|fixme|hack|xxx)/i,
  },
  {
    id: 'GEI-001',
    tool: 'cargo-geiger',
    severity: 'high',
    title: 'Unsafe block detected',
    description: 'Unsafe code bypasses Rust compiler safety guarantees.',
    remediation: 'Remove unsafe code where possible. Otherwise add a SAFETY comment and tests covering invariants.',
    pattern: /\bunsafe\s*\{/,
  },
  {
    id: 'GEI-002',
    tool: 'cargo-geiger',
    severity: 'medium',
    title: 'Unsafe function detected',
    description: 'Unsafe functions push invariant requirements onto every caller.',
    remediation: 'Wrap unsafe functions in a safe API that validates preconditions.',
    pattern: /\bunsafe\s+fn\s+\w+/,
  },
  {
    id: 'AUD-001',
    tool: 'cargo-audit',
    severity: 'high',
    title: 'Vulnerable curve25519-dalek dependency',
    description: 'curve25519-dalek versions below 4.x are commonly affected by older advisory classes.',
    remediation: 'Upgrade curve25519-dalek to the latest 4.x release and re-run cargo audit.',
    pattern: /curve25519-dalek\s*=\s*["']?[0-3]\./,
    filePattern: /(^|\/)Cargo\.toml$/,
  },
  {
    id: 'AUD-002',
    tool: 'cargo-audit',
    severity: 'medium',
    title: 'Outdated Solana program SDK',
    description: 'Older solana-program releases miss security fixes and runtime compatibility updates.',
    remediation: 'Upgrade solana-program and Anchor together, then run the full test suite.',
    pattern: /solana-program\s*=\s*["']?1\.(1[0-6])\./,
    filePattern: /(^|\/)Cargo\.toml$/,
  },
  {
    id: 'AUD-003',
    tool: 'cargo-audit',
    severity: 'info',
    title: 'Older Anchor dependency',
    description: 'Older Anchor versions lack newer account validation and IDL improvements.',
    remediation: 'Upgrade anchor-lang to the latest compatible release.',
    pattern: /anchor-lang\s*=\s*["']?0\.(2[0-9]|30)\./,
    filePattern: /(^|\/)Cargo\.toml$/,
  },
];

module.exports = { rules, tools };
