import React from 'react';
import { Download } from 'lucide-react';

const ReportPreview: React.FC = () => {
  return (
    <>
      <div className="screen-wrap report-screen">
        <div className="glass-panel">
          <div className="topbar">
            <span className="report-toolbar-title">Audit Report Preview</span>
            <div className="report-actions">
              <button className="btn btn-secondary">Print</button>
              <button className="btn btn-primary">
                <Download size={14} />
                Save PDF
              </button>
            </div>
          </div>
          <div className="report-page">
            <div className="report-header">
              <div>
                <div className="report-kicker">Automated Security Audit</div>
                <div className="report-title">my-staking-contract</div>
                <div className="report-meta">
                  Scanned: May 12, 2026 · Tools: cargo-audit v0.21, geiger v0.11, Clippy
                  2024, Aderyn v0.3
                </div>
              </div>
              <span className="report-stamp">7 Findings</span>
            </div>

            <div className="stat-row">
              <div className="stat-card">
                <div className="stat-num text-critical">2</div>
                <div className="stat-label">Critical</div>
              </div>
              <div className="stat-card">
                <div className="stat-num text-high">1</div>
                <div className="stat-label">High</div>
              </div>
              <div className="stat-card">
                <div className="stat-num text-medium">3</div>
                <div className="stat-label">Medium</div>
              </div>
              <div className="stat-card">
                <div className="stat-num text-low">0</div>
                <div className="stat-label">Low</div>
              </div>
              <div className="stat-card">
                <div className="stat-num text-info">1</div>
                <div className="stat-label">Info</div>
              </div>
            </div>

            <table className="findings-table">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Severity</th>
                  <th>Title</th>
                  <th>Source</th>
                  <th>Location</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="report-mono">SSW-001</td>
                  <td>
                    <span className="sev-chip sev-critical">CRITICAL</span>
                  </td>
                  <td className="report-strong">Missing account owner check — stake()</td>
                  <td>Aderyn</td>
                  <td className="report-mono">lib.rs:5</td>
                </tr>
                <tr>
                  <td className="report-mono">SSW-004</td>
                  <td>
                    <span className="sev-chip sev-critical">CRITICAL</span>
                  </td>
                  <td className="report-strong">Missing signer check on authority</td>
                  <td>Aderyn</td>
                  <td className="report-mono">lib.rs:5</td>
                </tr>
                <tr>
                  <td className="report-mono">RUS-12</td>
                  <td>
                    <span className="sev-chip sev-high">HIGH</span>
                  </td>
                  <td className="report-strong">Vulnerable dependency: curve25519-dalek</td>
                  <td>cargo-audit</td>
                  <td className="report-mono">Cargo.toml</td>
                </tr>
                <tr>
                  <td className="report-mono">CLY-03</td>
                  <td>
                    <span className="sev-chip sev-medium">MEDIUM</span>
                  </td>
                  <td className="report-strong">Unchecked arithmetic in reward calculation</td>
                  <td>Clippy</td>
                  <td className="report-mono">lib.rs:8</td>
                </tr>
              </tbody>
            </table>

            <div className="report-footer-note">
              Generated by Solana Security Workbench · Not a substitute for manual audit
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default ReportPreview;
